pipeline:
  name: allure
  identifier: allure
  projectIdentifier: pranavt1
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: pranavgithub
        repoName: allure-cucumber-example
        build: <+input>
  stages:
    - stage:
        name: build
        identifier: build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: run
                  identifier: run
                  spec:
                    shell: Sh
                    command: |-
                      echo hi
                      echo hi
                      ruby -v
                      gem install bundler
                      bundle install
                      bundle exec cucumber
